
# Uncomment this line to define a global platform for your project
 platform :ios, ‘9.0’


target ‘YLTestCode’ do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for SwiftDemo
    pod 'YLSwiftScan'
    pod 'YLBanner'
    pod 'YLRecordingVideo'
#    pod 'BabyBluetooth'
    #pod 'YLAuxiliaryKit'
    
#    pod 'AMap3DMap'
#    pod 'AMapLocation'
#    pod 'AMapNavi'
#    pod 'AMapSearch'
     pod 'SnapKit'
     #pod 'YYKit'
     pod 'FMDB'
     pod 'Kingfisher'
     pod 'TZImagePickerController'
     pod 'ObjectMapper'
#    pod 'XHLaunchAd'
#    
end
