
# Podfile
use_frameworks!

target 'YLSwiftTest' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Kingfisher'
      pod 'SnapKit'
end

# RxTests 和 RxBlocking 将在单元/集成测试中起到重要作用
#target 'YLSwiftTest' do
#    pod 'RxBlocking', '~> 4.0'
#    pod 'RxTest',     '~> 4.0'
#end
