
# Podfile
use_frameworks!

target 'YLSwiftTest' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Kingfisher'
    pod 'SnapKit'
    
    
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    #友盟统计和分享
    #pod 'UMengAnalytics'
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'
    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'
    # 集成短信
    pod 'UMCShare/Social/SMS'
    
    
    
    pod 'BaiduMapKit' #百度地图SDK
    pod 'BMKLocationKit' #定位功能
    
end

# RxTests 和 RxBlocking 将在单元/集成测试中起到重要作用
#target 'YLSwiftTest' do
#    pod 'RxBlocking', '~> 4.0'
#    pod 'RxTest',     '~> 4.0'
#end
