source "https://github.com/CocoaPods/Specs.git"
platform :ios, "9.0"

target "FaceRecognition" do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'FMDB'
    pod 'SDWebImage'
    pod 'SSKeychain'
    pod 'YYModel'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'PNChart'

end


